# Generated by Django 4.2.7 on 2023-11-25 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_endereco_options'),
        ('core', '0003_pontosturistico_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
