# Generated by Django 3.2.18 on 2023-11-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pontosturistico_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
