# Generated by Django 4.2.7 on 2023-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linha1", models.CharField(max_length=150)),
                ("linha2", models.CharField(blank=True, max_length=150, null=True)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
                ("latitude", models.CharField(blank=True, max_length=100, null=True)),
                ("longitude", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Endereços",
            },
        ),
    ]
