# Generated by Django 4.2.7 on 2023-11-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereços'},
        ),
    ]
