# Generated by Django 4.2.7 on 2023-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("horario_func", models.TextField()),
                ("idade_minima", models.IntegerField()),
                ("foto", models.FileField(blank=True, null=True, upload_to="atracoes")),
            ],
            options={
                "verbose_name_plural": "Atrações e Recursos",
            },
        ),
    ]
