# Generated by Django 4.2.7 on 2023-11-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atrações'},
        ),
    ]
