# Generated by Django 4.2.7 on 2023-11-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_alter_atracao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atrações e Recursos'},
        ),
    ]
